// <auto-generated />
using System;
using App.Infrastructure.Core.DataBaseContext.Connection;
using App.Shared.Common.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Infrastructure.Core.DataBaseContext.Migrations
{
    [DbContext(typeof(AppDataBaseContext))]
    [Migration("20260923182348_AddDevicesRegistry")]
    partial class AddDevicesRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "user_role_enum", new[] { "member", "moderator", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "auth", "user_status_enum", new[] { "active", "inactive", "suspended" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fleet", "vehicle_state_enum", new[] { "offline", "disponible", "en_carga", "en_ruta", "detenido", "en_descarga", "fuera_de_servicio" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "geofences", "geofence_kind_enum", new[] { "load", "unload", "wait", "restricted", "checkpoint", "custom" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notifications", "notification_type_enum", new[] { "info", "success", "warning", "error" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tracking", "event_severity_enum", new[] { "info", "warning", "critical" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tracking", "tracking_event_type_enum", new[] { "geofence_entered", "geofence_exited", "speed_limit_exceeded", "speed_limit_cleared", "route_deviation_detected", "route_deviation_cleared", "long_stop_detected", "long_stop_ended", "trip_started", "trip_completed", "trip_cancelled", "gps_connection_lost", "gps_connection_restored" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tracking", "trip_status_enum", new[] { "active", "completed", "cancelled", "incomplete" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_credential", "verification_type_enum", new[] { "email_confirmation", "password_reset" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Vehicles.Entities.TDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identifier");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique();

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("devices", "fleet");
                });

            modelBuilder.Entity("App.Domain.Geofences.Entities.TGeofence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<Polygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (polygon)")
                        .HasColumnName("geometry");

                    b.Property<GeofenceKind>("Kind")
                        .HasColumnType("geofences.geofence_kind_enum")
                        .HasColumnName("kind");

                    b.Property<decimal?>("MaxSpeedKmh")
                        .HasColumnType("numeric")
                        .HasColumnName("max_speed_kmh");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("geofences", "geofences");
                });

            modelBuilder.Entity("App.Domain.Materials.Entities.TMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("materials", "materials");
                });

            modelBuilder.Entity("App.Domain.Notifications.Entities.TNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.Property<NotificationType>("Type")
                        .HasColumnType("notifications.notification_type_enum")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("notifications", "notifications");
                });

            modelBuilder.Entity("App.Domain.Routes.Entities.TMineRoad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<LineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (linestring)")
                        .HasColumnName("geometry");

                    b.Property<int?>("MaxSpeedKmh")
                        .HasColumnType("integer")
                        .HasColumnName("max_speed_kmh");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("mine_roads", "roads");
                });

            modelBuilder.Entity("App.Domain.Routes.Entities.TRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<int>("AlternativeRank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("alternative_rank");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid?>("DestinationGeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_geofence_id");

                    b.Property<LineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (linestring)")
                        .HasColumnName("geometry");

                    b.Property<int?>("MaxSpeedKmh")
                        .HasColumnType("integer")
                        .HasColumnName("max_speed_kmh");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OriginGeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_geofence_id");

                    b.Property<Guid?>("RouteGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_group_id");

                    b.Property<string>("SpeedProfileJson")
                        .HasColumnType("text")
                        .HasColumnName("speed_profile_json");

                    b.Property<int>("ToleranceM")
                        .HasColumnType("integer")
                        .HasColumnName("tolerance_m");

                    b.Property<string>("WaypointsJson")
                        .HasColumnType("text")
                        .HasColumnName("waypoints_json");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DestinationGeofenceId");

                    b.HasIndex("OriginGeofenceId");

                    b.HasIndex("RouteGroupId");

                    b.ToTable("routes", "routes");
                });

            modelBuilder.Entity("App.Domain.Tracking.Entities.TGpsPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<Point>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry (point)")
                        .HasColumnName("geometry");

                    b.Property<decimal?>("Hdop")
                        .HasColumnType("numeric")
                        .HasColumnName("hdop");

                    b.Property<short?>("HeadingDeg")
                        .HasColumnType("smallint")
                        .HasColumnName("heading_deg");

                    b.Property<bool?>("Ignition")
                        .HasColumnType("boolean")
                        .HasColumnName("ignition");

                    b.Property<decimal?>("OdometerKm")
                        .HasColumnType("numeric")
                        .HasColumnName("odometer_km");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<short?>("Satellites")
                        .HasColumnType("smallint")
                        .HasColumnName("satellites");

                    b.Property<decimal?>("SpeedKmh")
                        .HasColumnType("numeric")
                        .HasColumnName("speed_kmh");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("VehicleId");

                    b.ToTable("gps_positions", "tracking");
                });

            modelBuilder.Entity("App.Domain.Tracking.Entities.TTrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofence_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<Point>("Position")
                        .HasColumnType("geometry (point)")
                        .HasColumnName("position");

                    b.Property<EventSeverity>("Severity")
                        .HasColumnType("tracking.event_severity_enum")
                        .HasColumnName("severity");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.Property<TrackingEventType>("Type")
                        .HasColumnType("tracking.tracking_event_type_enum")
                        .HasColumnName("type");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("GeofenceId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TripId");

                    b.HasIndex("VehicleId");

                    b.ToTable("tracking_events", "tracking");
                });

            modelBuilder.Entity("App.Domain.Tracking.Entities.TTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("DestinationGeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_geofence_id");

                    b.Property<int>("DeviationCount")
                        .HasColumnType("integer")
                        .HasColumnName("deviation_count");

                    b.Property<decimal?>("DistanceKm")
                        .HasColumnType("numeric")
                        .HasColumnName("distance_km");

                    b.Property<int?>("DurationS")
                        .HasColumnType("integer")
                        .HasColumnName("duration_s");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<decimal?>("LoadTonnes")
                        .HasColumnType("numeric")
                        .HasColumnName("load_tonnes");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<decimal?>("MaxSpeedKmh")
                        .HasColumnType("numeric")
                        .HasColumnName("max_speed_kmh");

                    b.Property<Guid?>("OriginGeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_geofence_id");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<int>("SpeedAlertCount")
                        .HasColumnType("integer")
                        .HasColumnName("speed_alert_count");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<TripStatus>("Status")
                        .HasColumnType("tracking.trip_status_enum")
                        .HasColumnName("status");

                    b.Property<LineString>("Track")
                        .HasColumnType("geometry (linestring)")
                        .HasColumnName("track");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DestinationGeofenceId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OriginGeofenceId");

                    b.HasIndex("RouteId");

                    b.HasIndex("Status");

                    b.HasIndex("VehicleId");

                    b.ToTable("trips", "tracking");
                });

            modelBuilder.Entity("App.Domain.User.Entities.TEmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CodeExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("code_expires_at");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("code_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<DateTime>("LinkExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("link_expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("token_hash");

                    b.Property<VerificationType>("Type")
                        .HasColumnType("user_credential.verification_type_enum")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("email_verifications", "user_credential");
                });

            modelBuilder.Entity("App.Domain.User.Entities.TPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("persons", "user_credential");
                });

            modelBuilder.Entity("App.Domain.User.Entities.TRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", "user_credential");
                });

            modelBuilder.Entity("App.Domain.User.Entities.TUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .HasColumnName("password");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", "user_credential");
                });

            modelBuilder.Entity("App.Domain.User.Entities.TUserGateway", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar")
                        .HasColumnName("provider_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_gateways", "user_credential");
                });

            modelBuilder.Entity("App.Domain.Vehicles.Entities.TVehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Point>("LastPosition")
                        .HasColumnType("geometry (point)")
                        .HasColumnName("last_position");

                    b.Property<DateTime?>("LastReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reported_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plate");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("vehicles", "fleet");
                });

            modelBuilder.Entity("App.Domain.Vehicles.Entities.TVehicleCurrentState", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<Guid?>("ActiveTripId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_trip_id");

                    b.Property<Guid?>("CurrentGeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_geofence_id");

                    b.Property<Point>("LastGeom")
                        .HasColumnType("geometry (point)")
                        .HasColumnName("last_geom");

                    b.Property<DateTime?>("LastReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received_at");

                    b.Property<DateTime?>("LastReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_recorded_at");

                    b.Property<DateTime?>("OffRouteSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("off_route_since");

                    b.Property<int>("OffRouteStreak")
                        .HasColumnType("integer")
                        .HasColumnName("off_route_streak");

                    b.Property<DateTime?>("OverSpeedSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("over_speed_since");

                    b.Property<VehicleState>("State")
                        .HasColumnType("fleet.vehicle_state_enum")
                        .HasColumnName("state");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("VehicleId");

                    b.ToTable("vehicle_current_state", "fleet");
                });

            modelBuilder.Entity("App.Infrastructure.Core.DataBaseContext.Audit.AuditMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_domain_events_occurred_at_utc");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_domain_events_type");

                    b.ToTable("domain_events", "audit");
                });

            modelBuilder.Entity("App.Domain.Routes.Entities.TRoute", b =>
                {
                    b.HasOne("App.Domain.Geofences.Entities.TGeofence", null)
                        .WithMany()
                        .HasForeignKey("DestinationGeofenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("App.Domain.Geofences.Entities.TGeofence", null)
                        .WithMany()
                        .HasForeignKey("OriginGeofenceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("App.Domain.Tracking.Entities.TGpsPosition", b =>
                {
                    b.HasOne("App.Domain.Vehicles.Entities.TVehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.Tracking.Entities.TTrackingEvent", b =>
                {
                    b.HasOne("App.Domain.Geofences.Entities.TGeofence", null)
                        .WithMany()
                        .HasForeignKey("GeofenceId");

                    b.HasOne("App.Domain.Tracking.Entities.TTrip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId");

                    b.HasOne("App.Domain.Vehicles.Entities.TVehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("App.Domain.Tracking.Entities.TTrip", b =>
                {
                    b.HasOne("App.Domain.Geofences.Entities.TGeofence", null)
                        .WithMany()
                        .HasForeignKey("DestinationGeofenceId");

                    b.HasOne("App.Domain.Materials.Entities.TMaterial", null)
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("App.Domain.Geofences.Entities.TGeofence", null)
                        .WithMany()
                        .HasForeignKey("OriginGeofenceId");

                    b.HasOne("App.Domain.Routes.Entities.TRoute", null)
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.HasOne("App.Domain.Vehicles.Entities.TVehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.User.Entities.TPerson", b =>
                {
                    b.HasOne("App.Domain.User.Entities.TUser", null)
                        .WithOne("Person")
                        .HasForeignKey("App.Domain.User.Entities.TPerson", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Domain.User.Entities.TRefreshToken", b =>
                {
                    b.HasOne("App.Domain.User.Entities.TUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Domain.User.Entities.TUserGateway", b =>
                {
                    b.HasOne("App.Domain.User.Entities.TUser", "User")
                        .WithMany("UserGateways")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Domain.Vehicles.Entities.TVehicleCurrentState", b =>
                {
                    b.HasOne("App.Domain.Vehicles.Entities.TVehicle", "Vehicle")
                        .WithOne("CurrentState")
                        .HasForeignKey("App.Domain.Vehicles.Entities.TVehicleCurrentState", "VehicleId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("App.Domain.User.Entities.TUser", b =>
                {
                    b.Navigation("Person")
                        .IsRequired();

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserGateways");
                });

            modelBuilder.Entity("App.Domain.Vehicles.Entities.TVehicle", b =>
                {
                    b.Navigation("CurrentState");
                });
#pragma warning restore 612, 618
        }
    }
}
